### ISSUE TITLE
[Apple M1][Fix] Installing hopsworks

### ISSUE THREAD

**Issue by arazvant** [iusztinpaul/energy-forecasting#1]
👋

First of all, great job @iusztinpaul & @kurtispykes.
I've seen that this code was tested on Ubuntu. In case anyone tries to reproduce/run this on an Apple M1 chip, you might encouter some issues while installing `hopsworks` pip package.

If you get this log:
<img width="834" alt="Screenshot 2023-05-03 at 19 20 47" src="https://user-images.githubusercontent.com/23241108/235978170-5c00d246-a827-4e0e-83ee-38c25aa50b9a.png">

----
You need to do the following:
1. Install librdkafka (librdkafka <-- confluent_kafka <-- hopsworks): `brew install librdkafka`
2. Check which version brew installed : `ls /opt/homebrew/Cellar/librdkafka`
3. Export this env variable: `export C_INCLUDE_PATH=/opt/homebrew/Cellar/librdkafka/VERSION/include` (replace VERSION with yours)
4. Export this env variable: `export LIBRARY_PATH=/opt/homebrew/Cellar/librdkafka/VERSION/lib` (replace VERSION with yours)

Run `poetry install` or `poetry add hopsworks` and it should be ok.

**Comment by iusztinpaul** [comment]
Thank you for the info! I will update the README with your observations.

**Comment by gao-hongnan** [comment]
Thanks @Joywalker, I've encountered the same error and your solution works. I've included a script to handle this specifically if you are on macOS M1/M2.

```bash
#!/bin/bash

# Fetch the utils.sh script from a URL and source it
UTILS_SCRIPT=$(curl -s https://raw.githubusercontent.com/gao-hongnan/common-utils/main/scripts/utils.sh)
source /dev/stdin <<<"$UTILS_SCRIPT"
logger "INFO" "Fetched the utils.sh script from a URL and sourced it"

resolve_hopswork() {
  # Install librdkafka
  brew install librdkafka

  # Get the version of librdkafka installed
  VERSION=$(ls /opt/homebrew/Cellar/librdkafka | tail -n 1)

  # Export necessary environment variables
  export C_INCLUDE_PATH=/opt/homebrew/Cellar/librdkafka/$VERSION/include
  export LIBRARY_PATH=/opt/homebrew/Cellar/librdkafka/$VERSION/lib
}

custom_install_hopswork_if_arm64() {
    # Check if on macOS with M1 or ARM chip
    if [[ "$(uname -m)" == "arm64" ]]; then
    logger "INFO" "Installing librdkafka for M1 chip"
    resolve_hopswork
    fi
}

main() {
    custom_install_hopswork_if_arm64

    # Set poetry to create virtual environments in the project's directory
    logger "INFO" "Setting poetry to create virtual environments in the project's directory"
    poetry config virtualenvs.in-project true

    # Activate the poetry environment and install dependencies
    logger "INFO" "Activating the poetry environment and installing dependencies"
    poetry shell
    poetry install
}

main
```

After running `feature-pipeline`, I notice that Homebrew installs an incompatible version that may lead to `SSL` errors down the road.

One solution referenced from this [issue](https://community.hopsworks.ai/t/ssl-handshake-failed-on-macos-hopsworks-serverless/886/3) is:

```bash
curl -O https://raw.githubusercontent.com/Homebrew/homebrew-core/f7d0f40bbc4075177ecf16812fd95951a723a996/Formula/librdkafka.rb
brew install --build-from-source librdkafka.rb
rm librdkafka.rb
```

Consequently, one can replace the line `brew install librdkafka` with the above commands to ensure hopswork work when interacting with the pipelines.

**Comment by arazvant** [comment]
> Thanks @Joywalker, I've encountered the same error and your solution works. I've included a script to handle this specifically if you are on macOS M1/M2.
> 
> ```shell
> #!/bin/bash
> 
> # Fetch the utils.sh script from a URL and source it
> UTILS_SCRIPT=$(curl -s https://raw.githubusercontent.com/gao-hongnan/common-utils/main/scripts/utils.sh)
> source /dev/stdin <<<"$UTILS_SCRIPT"
> logger "INFO" "Fetched the utils.sh script from a URL and sourced it"
> 
> resolve_hopswork() {
>   # Install librdkafka
>   brew install librdkafka
> 
>   # Get the version of librdkafka installed
>   VERSION=$(ls /opt/homebrew/Cellar/librdkafka | tail -n 1)
> 
>   # Export necessary environment variables
>   export C_INCLUDE_PATH=/opt/homebrew/Cellar/librdkafka/$VERSION/include
>   export LIBRARY_PATH=/opt/homebrew/Cellar/librdkafka/$VERSION/lib
> }
> 
> custom_install_hopswork_if_arm64() {
>     # Check if on macOS with M1 or ARM chip
>     if [[ "$(uname -m)" == "arm64" ]]; then
>     logger "INFO" "Installing librdkafka for M1 chip"
>     resolve_hopswork
>     fi
> }
> 
> main() {
>     custom_install_hopswork_if_arm64
> 
>     # Set poetry to create virtual environments in the project's directory
>     logger "INFO" "Setting poetry to create virtual environments in the project's directory"
>     poetry config virtualenvs.in-project true
> 
>     # Activate the poetry environment and install dependencies
>     logger "INFO" "Activating the poetry environment and installing dependencies"
>     poetry shell
>     poetry install
> }
> 
> main
> ```

That's awesome @gao-hongnan! 🚀 
Thanks for your completion, will surely help lots!

**Comment by chen-bowen** [comment]
doesn't work for me. Still getting 
```
OSError: dlopen(/Users/bowen.chen/Library/Caches/pypoetry/virtualenvs/training-pipeline-ckjbU_s7-py3.9/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: <D21A7969-4567-3BC7-94ED-6A9E83AE9D78> /Users/bowen.chen/Library/Caches/pypoetry/virtualenvs/training-pipeline-ckjbU_s7-py3.9/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so
  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache)
```
I'm on Apple M1
