### ISSUE TITLE
Hopsworks can't create projects, can't find API keys

### ISSUE THREAD

**Issue by chen-bowen** [iusztinpaul/energy-forecasting#11]
there seems to be a change in the hopworks UI, now I can't seem to create new projects, as there's no create project button.
<img width="1581" alt="image" src="https://github.com/iusztinpaul/energy-forecasting/assets/18410378/c84c46f1-36a1-4e29-9b82-3f8af64bda5c">

Also, I tried to create an API key from here

<img width="1413" alt="image" src="https://github.com/iusztinpaul/energy-forecasting/assets/18410378/a301504f-4e88-405e-a432-3221194f7f17">

but I kept on getting this error

```
RestAPIError: Metadata operation error: (url: https://c.app.hopsworks.ai/hopsworks-api/api/project). Server response: 
HTTP code: 401, HTTP reason: Unauthorized, body: b'{"errorCode":320002,"errorMsg":"Api key not found"}', error code: 320002, error msg: Api key not found, user msg: 
```

Any ideas?

**Comment by iusztinpaul** [comment]
You can use the project created by default.

As for the API Key, I personally don't have access to the new UI (the one you shared). Are you 100% you accessed the right service?

Just in case --> [Here is where you can log in to Hopsworks.](https://app.hopsworks.ai/app)

**Comment by chen-bowen** [comment]
using your link I'm getting this
<img width="1722" alt="image" src="https://github.com/iusztinpaul/energy-forecasting/assets/18410378/a99c551e-1ce9-4909-a05e-80129f1650a1">

**Comment by iusztinpaul** [comment]
Probably it redirected me to another page and copied the wrong link.

What link have you accessed & steps have you tried to access Hopsworks and create the API key?

BTW, they are a fast-growing start-up. Maybe you must wait 1-2 days to solve their issue.

**Comment by iusztinpaul** [comment]
Have you fixed this issue? I am asking to know if I can close the issue or not.
