### ISSUE TITLE
Error while running training-pipeline because it is not being able to find libomp.dylib

### ISSUE THREAD

**Issue by VATUL123** [iusztinpaul/energy-forecasting#15]
First of all, great work Paul!
I am running on Apple M1.
I was able to run the feature-pipeline without any issues. However when I run,
python -m training_pipeline.hyperparameter_tuning
as part of training-pipeline, I get the following error:

OSError: dlopen(/Users/vatulparakh/Library/Caches/pypoetry/virtualenvs/training-pipeline-8avOwJ3R-py3.9/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: '/usr/local/opt/libomp/lib/libomp.dylib'
Referenced from: '/Users/vatulparakh/Library/Caches/pypoetry/virtualenvs/training-pipeline-8avOwJ3R-py3.9/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so'
Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file)

Looks like some problem with it not being able to find the libomp library. Although I have this file in the following location:
/opt/homebrew/opt/libomp/lib

**Comment by VATUL123** [comment]
@iusztinpaul 
Checking in if you got time to look into this?
cc: @gao-hongnan If you have any suggestions here?

**Comment by gao-hongnan** [comment]
> @iusztinpaul 
> 
> Checking in if you got time to look into this?
> 
> cc: @gao-hongnan If you have any suggestions here?

Hi there, have you tried the solution mentioned in this issue #1 [here](https://github.com/iusztinpaul/energy-forecasting/issues/1)?

**Comment by gao-hongnan** [comment]
> @iusztinpaul 
> 
> Checking in if you got time to look into this?
> 
> cc: @gao-hongnan If you have any suggestions here?

Hi there, thanks for the question. Can I check if you have followed the steps in issue #12 [here](https://github.com/iusztinpaul/energy-forecasting/issues/12)?

**Comment by VATUL123** [comment]
Thanks for looking into this @gao-hongnan. I followed the steps i.e installed cmake and libomp but that did not seem to work. However, I can see the required file in the following location:
/opt/homebrew/opt/libomp/lib/libomp.dylib

**Comment by gao-hongnan** [comment]
Hi @VATUL123, do you think you can try uninstalling it and installing it again. Here's one very similar [post](https://stackoverflow.com/questions/72285089/i-am-not-able-to-run-lightgbm-on-mac-because-of-an-oserror-libomp-dylib-no-su).

**Comment by iusztinpaul** [comment]
Sorry for the late reply, @VATUL123. Thank you, @gao-hongnan for helping @VATUL123.

Unfortunately, I can't help you out on this one @VATUL123, as I haven't tested the code on Apple M1. @gao-hongnan  is the master of this topic.

**Comment by VATUL123** [comment]
Thanks @iusztinpaul and @gao-hongnan 
This seems to have solved the issue for now:

git clone --recursive https://github.com/microsoft/LightGBM
cd LightGBM
mkdir build
cd build
cmake -DUSE_OPENMP=OFF ..
make -j4

sh ./build-python.sh install —nomp

I am not sure if I need to do anything to add this to poetry.

**Comment by iusztinpaul** [comment]
Happy it worked! Happy learning. 

I will close the issue.
