### ISSUE TITLE
Question on the location of Batch Prectiction in the Batch Architecture

### ISSUE THREAD

**Issue by jnsofini** [iusztinpaul/energy-forecasting#2]
Hello Paul,

First thank you for the great work putting in the Full Stack ML Series together. I was going through the [first of the seven](https://towardsdatascience.com/a-framework-for-building-a-production-ready-feature-engineering-pipeline-f0b29609b20f) and was wondering why you placed the Batch Prediction before the Training, [see fig.](https://miro.medium.com/v2/resize:fit:720/format:webp/1*yXBLjC2fwvLl45suEyzjsw.png) Could you throw more light on that if you have time.

Thank you.

**Comment by iusztinpaul** [comment]
Hello,

Thank you for reaching out.

That is a mistake. Thank you for highlighting it. You are right, the training pipeline should be before the batch prediction pipeline. 

I uploaded an outdated diagram.

I will update the diagram with the correct version.

Thank you!

**Comment by jnsofini** [comment]
Great! Thanks for good work.
