### ISSUE TITLE
Is it possible to follow this course on a Windows machine?

### ISSUE THREAD

**Issue by soliverc** [iusztinpaul/energy-forecasting#25]
I am a noob at Linux. 

99% of everything I have done in Machine Learning has been via Anaconda on Windows (yes I know, also noob).

Can this course be done on windows, or would it be a headache?

Do you recommend I follow this on a virtual Linux machine?

**Comment by iusztinpaul** [comment]
Hello,

You won't have any CUDA dependencies to install. Thus, I think it will work entirely out of the box. Maybe use Windows WSL to be 100% sure everything works fine.

Excited to consider taking my course, and let me know if you have any other questions.
