### ISSUE TITLE
ml_pipeline DAG not running

### ISSUE THREAD

**Issue by FUenal** [iusztinpaul/energy-forecasting#27]
Hi Paul,

Many thanks for the amazing course!  The issue I encounter is that the ml_pipeline DAG is not running in Airflow (see screenshots).

<img width="1698" alt="Screenshot 2024-02-13 at 15 05 04" src="https://github.com/iusztinpaul/energy-forecasting/assets/18496483/7f986a6a-ec52-40b2-9b7d-72b1dbeb559d">

<img width="1660" alt="Screenshot 2024-02-13 at 15 20 59" src="https://github.com/iusztinpaul/energy-forecasting/assets/18496483/21be5be2-29c9-4e72-942c-80c57ebd4225">

When running 'docker compose up airflow-init', I don't get an error message but a warning which I don't know what to do about (see screenshot)
<img width="1329" alt="Screenshot 2024-02-13 at 15 27 27" src="https://github.com/iusztinpaul/energy-forecasting/assets/18496483/b9c9522b-763c-4775-8ed9-3c666cb525f3">

I would appreciate your support to solve this. Thanks so much in advance!

**Comment by iusztinpaul** [comment]
Hello @FUenal,

I am excited you are doing my course.

Can you please click on the failed `run_feature_pipeline` step and access the logs? There, you will see exactly what happened. After, please send the logs here to see what is going on. 

My intuition is that there is some issue with Hopsworks or the credentials.

**Comment by FUenal** [comment]
Hello @iusztinpaul , 
Thanks for getting back to me on this! Attached are the logs for the ` run_feature_pipeline` step. Don't know what is going on. Thanks!

[dag_id=ml_pipeline_run_id=scheduled__2024-02-13T13 00 00+00 00_task_id=run_feature_pipeline_attempt=1.log](https://github.com/iusztinpaul/energy-forecasting/files/14302753/dag_id.ml_pipeline_run_id.scheduled__2024-02-13T13.00.00%2B00.00_task_id.run_feature_pipeline_attempt.1.log)

**Comment by iusztinpaul** [comment]
It looks like you haven't correctly configured the `.env` file under your `airflow` directory. Note that this is a different `.env` file than the one from the root folder.

Follow these steps to get the main idea of it: https://github.com/iusztinpaul/energy-forecasting?tab=readme-ov-file#the-pipeline

**Comment by FUenal** [comment]
Hi @iusztinpaul , re-doing the .env file under airflow did help, thanks! However, now the pipeline runs only partially (see screenshot).
<img width="1701" alt="Screenshot 2024-02-16 at 14 48 37" src="https://github.com/iusztinpaul/energy-forecasting/assets/18496483/a729cc06-e183-4e46-b556-381669f429b9">

Sending you the log for the train_from_best_c
[dag_id=ml_pipeline_run_id=manual__2024-02-16T13 23 42.766166+00 00_task_id=train_from_best_config_attempt=1.log](https://github.com/iusztinpaul/energy-forecasting/files/14311781/dag_id.ml_pipeline_run_id.manual__2024-02-16T13.23.42.766166%2B00.00_task_id.train_from_best_config_attempt.1.log)
onfig (red). The log error message says: RuntimeError: No best config found. Please run hyperparameter tuning first. Not sure it is related, but following your tutorial I added a variable to admin setting `ml_pipeline_should_run_hyperparameter_tuning = False` 
Log file attached.
Thanks for your efforts!

**Comment by iusztinpaul** [comment]
You need to run it once with “true” so it finds the best config with hyperparameter tuning

After, you can set it to false so it will always use the best config. 

Let me know how it works ✌️

**Comment by FUenal** [comment]
Hi @iusztinpaul , yes, that was it! Thanks!
The hyper parameter tuning step: how long is supposed to take on average?
I interrupted it yesterday, after 4 hours runtime. Is 4 hours+ regular?
Cheers

**Comment by iusztinpaul** [comment]
I am excited to see it finally works. Remember that you can contribute with the Docker image fix to benefit others. 

It depends greatly on your compute power, the model you use, and your search hyperparameter space.

For the sake of your example, you can reduce the search hyperparameter space from this config so it will run faster: **https://github.com/iusztinpaul/energy-forecasting/blob/main/training-pipeline/training_pipeline/configs/gridsearch.py**

**Comment by FUenal** [comment]
Hi Paul,
Existing indeed! App is up and running locally :-) This issue is answered and can be closed.

Thanks for the tip with hyper parameter tuning; makes sense with compute power of course! Appreciate your support and fast responses!

Happy to contribute with the Docker image fix soon!

Cheers
