### ISSUE TITLE
Homebrew overwriting Path, making poetry dysfunctional

### ISSUE THREAD

**Issue by LearnerSJ** [iusztinpaul/energy-forecasting#3]
Hi, thanks @iusztinpaul and @kurtispykes for all your hardwork in here and helping noobies like me. 

I am stuck at the installation step. I downloaded Poetry using curl -sSL https://install.python-poetry.org | python3 - and changed the path as well. It worked fine until I installed homebrew for installation of Apache. This changed the Path in .zprofile / .bashrc and now I do not know how to go about this. Would appreciate any help here. 

P.S - I got this error :zsh: command not found: poetry

**Comment by LearnerSJ** [comment]
I am using Macbook Air, Ventura 13.3.1 OS. I did not download Poetry using Homebrew because [this](https://stackoverflow.com/questions/73365780/why-is-not-recommended-to-install-poetry-with-homebrew) article strictly warns against doing that. Is there another way that I could download Apache httd without using Homebrew.

**Comment by iusztinpaul** [comment]
Hello @LearnerSJ,

I think you may find this [issue](https://github.com/iusztinpaul/energy-forecasting/issues/1) helpful.

Let me know if it works.
