### ISSUE TITLE
Improve Poetry Environment Setup and Documentation.

### ISSUE THREAD

**Issue by gao-hongnan** [iusztinpaul/energy-forecasting#4]
This potential PR introduces several improvements to the setup and documentation of the
Poetry environment:

-   **Poetry Environment Setup Scripts:** Added scripts to facilitate the
    setting up of the Poetry environment, making it easier for users to get
    started.

-   **Documentation Update:** Updated the `README.md` in the `feature-pipeline`
    directory to reflect the setup of the Poetry environment. This makes it
    easier for new users to understand how to set up and use the Poetry
    environment.

Here's one other proposal:

-   **Hopswork Project Name:** Consider add Hopswork Project Name to `.env`
    file. I tried to create the project name as `energy_consumption` but unexpectedly, Hopswork
    said the project name is taken. Let me know if this proposal is a sensible change.

The changes can be viewed [here](https://github.com/gao-hongnan/energy-forecasting/tree/dev/feature-pipeline) and [here for the scripts](https://github.com/gao-hongnan/energy-forecasting/tree/dev/scripts/devops/virtual_environment).

**Comment by iusztinpaul** [comment]
Hello, I will soon add your proposals. I am curious if you fixed the Hopsworks `Project Name Issue`?

**Comment by gao-hongnan** [comment]
> Hello, I will soon add your proposals. I am curious if you fixed the Hopsworks `Project Name Issue`?

Hello! It was my first time using Hopswork, and when I keyed in the same name as yours, it mentioned that I cannot use that name. When I changed the name to something else, it passed. I was also surprised because I thought project name should just be unique within personal account and not globally.

**Comment by iusztinpaul** [comment]
Yeah. I thought that too. I will double-check if this is still an issue. 

Have you modified your code to support a customized Hopsworks project name?

**Comment by gao-hongnan** [comment]
> Yeah. I thought that too. I will double-check if this is still an issue.
> 
> Have you modified your code to support a customized Hopsworks project name?

I think during the walkthrough of your tutorial, I just included it as a variable in `.env` file and call it instead.

**Comment by gao-hongnan** [comment]
> Yeah. I thought that too. I will double-check if this is still an issue.
> 
> Have you modified your code to support a customized Hopsworks project name?

Something like the below:

```python
 project = hopsworks.login(
     api_key_value=settings.SETTINGS["FS_API_KEY"],
     project=settings.SETTINGS["FS_PROJECT_NAME"],
 )
```

**Comment by iusztinpaul** [comment]
I asked Hopsworks to clarify this before making this modification. But thank you for pointing it out. Appreciate it.

**Comment by iusztinpaul** [comment]
I added the scripts & docs to the README. I also contacted Hopsworks regarding the `project_name` issue. I noted it down, and based on their response, I will adapt the code accordingly.

**Comment by gao-hongnan** [comment]
> I added the scripts & docs to the README. I also contacted Hopsworks regarding the `project_name` issue. I noted it down, and based on their response, I will adapt the code accordingly.

Thank you!

**Comment by iusztinpaul** [comment]
I solved the project name issue. 

You can add your Hopsworks project name in the `.env` file under the `FS_PROJECT_NAME = "<your-feature-store-project-name>"` variable.

Thanks again for the support. It is really appreciated.
