### ISSUE TITLE
Hopsworks project name

### ISSUE THREAD

**Issue by nipunikajain** [iusztinpaul/energy-forecasting#6]
Hi, you have mentioned to name the project as energy_consumption specifically over hops works but when trying to create a project with the mentioned name, I am getting message "This project name is already taken."

can you help me out here what can be done please?

**Comment by iusztinpaul** [comment]
Hello,

Unfortunately, this is an issue I have to fix. I will adapt the code + docs in the next few days, but until then, you can safely choose any name you wish and change the `hopsworks.login` calls with your new name.

Here is an example:
```python
project = hopsworks.login(
        api_key_value=settings.SETTINGS["FS_API_KEY"], project="<your_hopsworks_project_name"
    )
```

Feel free to let me know if you have any more questions.

**Comment by iusztinpaul** [comment]
I solved the project name issue. Pull the latest code and...

You can add your Hopsworks project name in the `.env` file under the `FS_PROJECT_NAME = "<your-feature-store-project-name>"` variable.

Let me know if you have any other questions.
