### ISSUE TITLE
'feature_group_id' error while running pipeline.py

### ISSUE THREAD

**Issue by VATUL123** [iusztinpaul/energy-forecasting#8]
Hey Paul,
 I am getting the following error while running 
 python3 -m feature_pipeline.pipeline

File "/Users/vatulparakh/Downloads/energy-forecasting/venv/lib/python3.9/site-packages/hsfs/feature_group.py", line 656, in expectation_suite
    self._expectation_suite = ExpectationSuite(**expectation_suite)
TypeError: __init__() got an unexpected keyword argument 'feature_group_id'

This was running just fine last week. But now, I see this error. How do I resolve this?

**Comment by iusztinpaul** [comment]
Hello,

I haven't seen the error before. 

Have you pulled the latest changes? I upgraded Hopsworks to 3.2.0

**Comment by VATUL123** [comment]
Yeah, probably some hopsworks upgrade issue. pulling in the latest changes and recreating the environment worked. Thanks
